# Generated by Django 5.0.4 on 2026-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_testmodel_count_testmodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('tshirts', 'Футболки'), ('shirts', 'Сорочка'), ('hoodies', 'Кофта'), ('sweaters', 'Светри'), ('jackets', 'Куртки'), ('coats', 'Пальто'), ('pants', 'Штани'), ('jeans', 'Джинси'), ('shorts', 'Шорти'), ('socks', 'Шкарпетки'), ('shoes', 'Взуття')], default='tshirts', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
