# Generated by Django 5.0.4 on 2026-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловіки'), ('female', 'Жінки'), ('child', 'Діти')], default='child', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('31.5', '31.5'), ('32', '32'), ('32.5', '32.5'), ('33', '33'), ('34', '34'), ('34.5', '34.5'), ('35', '35'), ('35.5', '35.5'), ('36', '36'), ('37', '37'), ('37.5', '37.5'), ('38', '38'), ('38.5', '38.5'), ('39', '39'), ('40', '40'), ('40.5', '40.5'), ('41', '41'), ('42', '42'), ('42.5', '42.5'), ('43', '43'), ('44', '44'), ('44.5', '44.5'), ('46', '46'), ('47', '47'), ('48', '48'), ('48.5', '48.5'), ('49.5', '49.5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('child', 'Діти')], default='', max_length=10),
        ),
    ]
